export enum DatabaseTablesEnum {
  USER_COLLECTION_NAME = 'User',
  GROUP_COLLECTION_NAME = 'Group',
  OAUTH_TOKEN_COLLECTION_NAME = 'Oauth_token',
  COURSE_COLLECTION_NAME = 'Course',
  MODULE_COLLECTION_NAME = 'Module',
  LESSON_COLLECTION_NAME = 'Lesson',
  QUESTION_COLLECTION_NAME = 'Question',
  CITY_COLLECTION_NAME = 'City',
  PASSED_LESSON_COLLECTION_NAME = 'Passed_lesson',
  PASSED_QUESTION_COLLECTION_NAME = 'Passed_question',
  COMMENT_COLLECTION_NAME = 'Comment'
}
